spring.application.name=eurekaserver
eureka.client.enabled=true 
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.dashboard.enabled=true
spring.profiles.active=${PROFILE}
thirdeye.resume.updater.api.key=${THIRDEYE_RESUME_UPDATER_API_KEY}
eureka.instance.instance-id=${spring.application.name}:${server.port}